// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiDJM6WKZ44zNlMo72j5pgRYCkrCq3WEc',
    appId: '1:761573357511:web:2a5e0dff5cef896de50be2',
    messagingSenderId: '761573357511',
    projectId: 'tictactoe-6c732',
    authDomain: 'tictactoe-6c732.firebaseapp.com',
    storageBucket: 'tictactoe-6c732.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgpUpPC4u7Dw3UePOq8PbNcnsksw6OsZo',
    appId: '1:761573357511:android:3adfd03fc45f41f9e50be2',
    messagingSenderId: '761573357511',
    projectId: 'tictactoe-6c732',
    storageBucket: 'tictactoe-6c732.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaA2AmDt0dWBrF0BUPJ5rAB1d0d5JM6WM',
    appId: '1:761573357511:ios:f31eb466775710d1e50be2',
    messagingSenderId: '761573357511',
    projectId: 'tictactoe-6c732',
    storageBucket: 'tictactoe-6c732.appspot.com',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaA2AmDt0dWBrF0BUPJ5rAB1d0d5JM6WM',
    appId: '1:761573357511:ios:f31eb466775710d1e50be2',
    messagingSenderId: '761573357511',
    projectId: 'tictactoe-6c732',
    storageBucket: 'tictactoe-6c732.appspot.com',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiDJM6WKZ44zNlMo72j5pgRYCkrCq3WEc',
    appId: '1:761573357511:web:6078aedd3a82372ae50be2',
    messagingSenderId: '761573357511',
    projectId: 'tictactoe-6c732',
    authDomain: 'tictactoe-6c732.firebaseapp.com',
    storageBucket: 'tictactoe-6c732.appspot.com',
  );
}
